# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNWWE4pAUTVgAePuE60rY9zo2EtUwxLb
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

st.set_page_config(page_title="Multi-Simulation Suite with ML", layout="wide")

# --------------------- LANDING PAGE ---------------------
st.title("🔬 Multi-Simulation Suite with ML Prediction")
st.write("""
This platform includes three simulations:
1. Epidemic Spread (SIR Model)
2. Traffic Flow (Cellular Automaton)
3. Forest Fire Spread (Grid CA)

The **ML Prediction** tab predicts future outcomes using Random Forest and Gradient Boosting models.
""")

# --------------------- TABS ---------------------
tab1, tab2, tab3, tab4 = st.tabs([
    "🦠 Epidemic Simulation",
    "🚗 Traffic Simulation",
    "🔥 Forest Fire Simulation",
    "🔮 ML Prediction"
])

# --------------------- GLOBAL DATA STORAGE ---------------------
# Simulation datasets
sim_data = {
    "epidemic": pd.DataFrame(),
    "traffic": pd.DataFrame(),
    "fire": pd.DataFrame(),
    "combined": pd.DataFrame()
}

# --------------------- 1. EPIDEMIC SIMULATION ---------------------
def run_sir_simulation(N, I0, beta, gamma, days):
    S, I, R = [N - I0], [I0], [0]
    data = []
    for day in range(days):
        new_infected = beta * S[-1] * I[-1] / N
        new_recovered = gamma * I[-1]
        S.append(S[-1] - new_infected)
        I.append(I[-1] + new_infected - new_recovered)
        R.append(R[-1] + new_recovered)
        data.append([day, S[-1], I[-1], R[-1]])
    return S, I, R, pd.DataFrame(data, columns=["day","susceptible","infected","recovered"])

with tab1:
    st.header("🦠 Epidemic Spread Simulation (SIR Model)")
    col1, col2 = st.columns(2)
    with col1:
        population = st.slider("Total Population", 100, 10000, 1000, key="sir_pop")
        I0 = st.slider("Initial Infected", 1, 500, 10, key="sir_i0")
        beta = st.slider("Infection Rate (β)", 0.01, 1.0, 0.3, key="sir_beta")
    with col2:
        gamma = st.slider("Recovery Rate (γ)", 0.01, 1.0, 0.1, key="sir_gamma")
        days = st.slider("Simulation Duration (Days)", 10, 300, 80, key="sir_days")
    if st.button("Run Epidemic Simulation", key="sir_run_btn"):
        S, I, R, df_epi = run_sir_simulation(population, I0, beta, gamma, days)
        sim_data["epidemic"] = df_epi.copy()
        df_epi["simulation"] = "epidemic"
        sim_data["combined"] = pd.concat([sim_data["combined"], df_epi], ignore_index=True)

        fig, ax = plt.subplots(figsize=(12,5))
        ax.plot(S, label='Susceptible', color='#1f77b4', linewidth=2)
        ax.plot(I, label='Infected', color='#d62728', linewidth=3)
        ax.plot(R, label='Recovered', color='#2ca02c', linewidth=2)
        peak_day = np.argmax(I)
        peak_val = max(I)
        ax.scatter(peak_day, peak_val, color='black', zorder=5)
        ax.text(peak_day, peak_val, f" Peak: {int(peak_val)}", fontsize=10)
        ax.set_title("SIR Epidemic Simulation", fontsize=16)
        ax.set_xlabel("Days", fontsize=14)
        ax.set_ylabel("Population", fontsize=14)
        ax.grid(True, linestyle='--', alpha=0.6)
        ax.legend()
        st.pyplot(fig)

# --------------------- 2. TRAFFIC SIMULATION ---------------------
def run_traffic_simulation(L, num_cars, vmax, p_slow, steps):
    road = np.zeros(L, dtype=int)
    positions = np.random.choice(L, num_cars, replace=False)
    for p in positions:
        road[p] = np.random.randint(0, vmax+1)
    history = []
    data = []
    for t in range(steps):
        history.append(road.copy())
        new_road = np.zeros(L, dtype=int)
        for i in range(L):
            if road[i] > 0 or (i>0 and road[i-1]>0):
                v = road[i]
                v = min(v+1, vmax)
                dist = 1
                while dist <= v and road[(i+dist)%L]==0:
                    dist+=1
                v = min(v, dist-1)
                if np.random.random() < p_slow:
                    v = max(v-1,0)
                new_pos = (i+v)%L
                new_road[new_pos] = v
        road = new_road
        avg_speed = road.mean()
        congestion = (road>0).sum()/L
        data.append([t, avg_speed, congestion])
    df = pd.DataFrame(data, columns=["time_step","avg_speed","congestion"])
    return np.array(history), df

with tab2:
    st.header("🚗 Traffic Flow Simulation (Cellular Automaton)")
    col1, col2 = st.columns(2)
    with col1:
        road_length = st.slider("Road Length", 20, 200, 50, key="traffic_length")
        num_cars = st.slider("Number of Cars", 1, 50, 10, key="traffic_cars")
    with col2:
        vmax = st.slider("Max Speed", 1, 10, 5, key="traffic_vmax")
        prob_slow = st.slider("Slow-down Probability", 0.0, 1.0, 0.3, key="traffic_prob")
        steps = st.slider("Simulation Steps", 10, 200, 60, key="traffic_steps")
    if st.button("Run Traffic Simulation", key="traffic_run_btn"):
        history, df_traffic = run_traffic_simulation(road_length, num_cars, vmax, prob_slow, steps)
        sim_data["traffic"] = df_traffic.copy()
        df_traffic["simulation"] = "traffic"
        sim_data["combined"] = pd.concat([sim_data["combined"], df_traffic], ignore_index=True)

        fig, ax = plt.subplots(figsize=(12,5))
        ax.imshow(history, aspect='auto', cmap='gray_r')
        ax.set_title("Traffic Flow Simulation\nWhite=Car, Black=Empty", fontsize=16)
        ax.set_xlabel("Road Position", fontsize=14)
        ax.set_ylabel("Time Step", fontsize=14)
        st.pyplot(fig)

# --------------------- 3. FOREST FIRE SIMULATION ---------------------
def forest_fire_step(grid, p_grow, p_lightning):
    new_grid = grid.copy()
    n, m = grid.shape
    for i in range(n):
        for j in range(m):
            if grid[i,j]==2:
                new_grid[i,j]=0
            elif grid[i,j]==1:
                if np.any(grid[max(0,i-1):min(n,i+2), max(0,j-1):min(m,j+2)]==2):
                    new_grid[i,j]=2
            elif grid[i,j]==0:
                if np.random.random() < p_grow:
                    new_grid[i,j]=1
            if grid[i,j]==1 and np.random.random()<p_lightning:
                new_grid[i,j]=2
    return new_grid

def run_forest_simulation(size, steps, p_grow, p_lightning):
    grid = np.zeros((size,size), dtype=int)
    history = []
    data = []
    for t in range(steps):
        history.append(grid.copy())
        burning_count = np.sum(grid==2)
        tree_count = np.sum(grid==1)
        data.append([t, burning_count, tree_count])
        grid = forest_fire_step(grid, p_grow, p_lightning)
    df = pd.DataFrame(data, columns=["time_step","burning","trees"])
    return np.array(history), df

with tab3:
    st.header("🔥 Forest Fire Spread Simulation")
    col1, col2 = st.columns(2)
    with col1:
        size = st.slider("Forest Size", 20, 150, 50, key="forest_size")
        steps_fire = st.slider("Simulation Steps", 10, 200, 60, key="forest_steps")
    with col2:
        p_grow = st.slider("Tree Growth Probability", 0.0, 1.0, 0.05, key="forest_grow")
        p_lightning = st.slider("Lightning Probability", 0.0, 1.0, 0.01, key="forest_light")
    if st.button("Run Forest Fire Simulation", key="forest_run_btn"):
        history, df_fire = run_forest_simulation(size, steps_fire, p_grow, p_lightning)
        sim_data["fire"] = df_fire.copy()
        df_fire["simulation"] = "fire"
        sim_data["combined"] = pd.concat([sim_data["combined"], df_fire], ignore_index=True)

        fig, ax = plt.subplots(figsize=(7,7))
        cmap = ListedColormap(["black","green","red"])
        ax.imshow(history[-1], cmap=cmap)
        ax.set_title("Forest Fire Simulation\nBlack=Empty | Green=Trees | Red=Fire", fontsize=16)
        ax.axis("off")
        st.pyplot(fig)

# --------------------- 4. ML PREDICTION TAB ---------------------
with tab4:
    st.header("🔮 ML Prediction (Random Forest & Gradient Boosting)")
    ml_choice = st.radio("Select Dataset for Prediction", ["Epidemic","Traffic","Forest Fire","Combined"])
    if ml_choice=="Epidemic" and not sim_data["epidemic"].empty:
        df = sim_data["epidemic"].copy()
        st.write("Epidemic Dataset Preview")
        st.dataframe(df.head())
        X = df[["day"]]
        y = df["infected"]
    elif ml_choice=="Traffic" and not sim_data["traffic"].empty:
        df = sim_data["traffic"].copy()
        st.write("Traffic Dataset Preview")
        st.dataframe(df.head())
        X = df[["time_step","avg_speed"]]
        y = df["congestion"]
    elif ml_choice=="Forest Fire" and not sim_data["fire"].empty:
        df = sim_data["fire"].copy()
        st.write("Forest Fire Dataset Preview")
        st.dataframe(df.head())
        X = df[["time_step","trees"]]
        y = df["burning"]
    elif ml_choice=="Combined" and not sim_data["combined"].empty:
        df = sim_data["combined"].copy()
        st.write("Combined Dataset Preview")
        st.dataframe(df.head())
        X = df.drop(columns=["simulation"])
        y = df.iloc[:,1]  # approximate target for demo
    else:
        st.warning("Run the corresponding simulation first!")
        X = y = None

    if X is not None and y is not None:
        if st.button("Run ML Prediction"):
            # Random Forest
            rf = RandomForestRegressor(n_estimators=100, random_state=42)
            rf.fit(X,y)
            pred_rf = rf.predict(X)
            # Gradient Boosting
            gb = GradientBoostingRegressor(n_estimators=100, random_state=42)
            gb.fit(X,y)
            pred_gb = gb.predict(X)

            # Error metrics
            metrics_df = pd.DataFrame({
                "Model":["Random Forest","Gradient Boosting"],
                "MAE":[mean_absolute_error(y,pred_rf), mean_absolute_error(y,pred_gb)],
                "MSE":[mean_squared_error(y,pred_rf), mean_squared_error(y,pred_gb)],
                "R2":[r2_score(y,pred_rf), r2_score(y,pred_gb)]
            })
            st.subheader("📊 Model Error Metrics")
            st.table(metrics_df)

            # Feature importance
            st.subheader("🌟 Feature Importance")
            fig, ax = plt.subplots(figsize=(8,4))
            if ml_choice=="Combined":
                features = X.columns
            else:
                features = X.columns
            importances = rf.feature_importances_
            ax.bar(features, importances, color="#1f77b4")
            ax.set_title("Random Forest Feature Importance")
            st.pyplot(fig)

            # Prediction plot
            st.subheader("📈 Predictions vs Actual")
            fig2, ax2 = plt.subplots(figsize=(12,5))
            ax2.plot(y.values, label="Actual", color="black")
            ax2.plot(pred_rf, label="RF Prediction", color="red")
            ax2.plot(pred_gb, label="GB Prediction", color="green")
            ax2.set_title("ML Predictions")
            ax2.set_xlabel("Samples")
            ax2.set_ylabel("Target Value")
            ax2.legend()
            st.pyplot(fig2)

            # Download CSV
            df_result = df.copy()
            df_result["RF_Prediction"] = pred_rf
            df_result["GB_Prediction"] = pred_gb
            csv = df_result.to_csv(index=False).encode()
            st.download_button("💾 Download Predictions CSV", data=csv, file_name=f"{ml_choice}_prediction.csv", mime="text/csv")